version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform init
          command: 'cd terraform_setup; terraform init'
      - run:
          name: Terraform plan
          command: 'cd terraform_setup; terraform plan -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION}'
  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform init
          command: 'cd terraform_setup; terraform init'
      - run:
          name: Terraform plan
          command: 'cd terraform_setup; terraform plan -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION}' -out=tf.plan
      - run:
          name: Terraform apply
          command: 'cd terraform_setup; terraform apply -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION}' -out=tf.plan -auto-approve
      - run:
          name: Terraform destroy
          command: 'cd terraform_setup; terraform destroy -auto-approve'
workflows:
  version: 2.1
  plan_and_apply:
    jobs:
      - plan:
          filters:
            branches:
              only:
                - develop
      - apply:
          filters:
            branches:
              only:
                - master



      