# Builds Dockerfile, pushes to ECR, and deploys to ECS
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  version: 2.1
  build_and_apply:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "AWS_ECR_URL"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: "AWS_DEFAULT_REGION"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: ${AWS_DEFAULT_REGION}
          family: "cwvlug_circleci_demo"
          cluster-name: "cwvlug_ecs_cluster"
          container-image-name-updates: "container=cwvlug-circleci-demo,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/cwvlug-circleci-demo:${CIRCLE_SHA1}"
          verify-revision-is-deployed: true



      