# Builds Dockerfile, pushes to ECR, and deploys to ECS
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  version: 2.1
  build_and_apply:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "AWS_ECR_URL"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: "AWS_DEFAULT_REGION"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
          region: AWS_DEFAULT_REGION



      