version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.10
jobs:
  build:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform init
          command: 'cd terraform_setup; terraform init'
      - run:
          name: Terraform plan
          command: 'cd terraform_setup; terraform plan'
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


      