version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@0.0.10
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform init
          command: 'cd terraform_setup; terraform init'
      - run:
          name: Terraform plan
          command: 'cd terraform_setup; terraform plan -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION}'
  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform init
          command: 'cd terraform_setup; terraform init'
      - run:
          name: Terraform plan
          command: 'cd terraform_setup; terraform plan -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION}'
      - run:
          name: Terraform apply
          command: 'cd terraform_setup; terraform apply -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION} -auto-approve'
      - run:
          name: Terraform destroy
          command: 'cd terraform_setup; terraform destroy -var aws_access_key=${AWS_ACCESS_KEY_ID} -var aws_secret_key=${AWS_SECRET_ACCESS_KEY} -var aws_region=${AWS_DEFAULT_REGION} -auto-approve'
workflows:
  version: 2.1
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: "AWS_ECR_URL"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: "AWS_DEFAULT_REGION"
          tag: "latest"
          create-repo: true
  plan_and_apply:
    jobs:
      - plan:
          requires: 
              - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - develop
      - apply:
          filters:
            branches:
              only:
                - master



      